---
title: "hw-03"
author: "Your Name (S000000)"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(scales)
```

### Exercise 1

```{r hw3-ex1}
library(readr)
pac_2000 <- read_csv("data/pac_2000.csv")
pac_2002 <- read_csv("data/pac_2002.csv")
pac_2004 <- read_csv("data/pac_2004.csv")
pac_2006 <- read_csv("data/pac_2006.csv")
pac_2008 <- read_csv("data/pac_2008.csv")
pac_2010 <- read_csv("data/pac_2010.csv")
pac_2012 <- read_csv("data/pac_2012.csv")
pac_2014 <- read_csv("data/pac_2014.csv")
pac_2016 <- read_csv("data/pac_2016.csv")
pac_2018 <- read_csv("data/pac_2018.csv")
pac_2020 <- read_csv("data/pac_2020.csv")

pac_all <- list(pac_2000, pac_2002, pac_2004, pac_2006, pac_2008, pac_2010, pac_2012, pac_2014, pac_2016, pac_2018, pac_2020)

  
Reduce(function(x, y) merge(x, y, all=TRUE), pac_all) 
 



```


2,194 observations and 7 variables

### Exercise 2

```{r hw3-ex2}
pac_all_backup <- read_csv("data/pac_all_backup.csv")
pac_all_backup %>% 
  separate(country_parent, into = c('Country', 'parent'), sep = "/" )

```



### Exercise 3

```{r hw3-ex3}
library(stringr)
pac_all_backup %>% 
  separate(country_parent, into = c('Country', 'parent'), sep = "/" )
col_um = c("[$]"='' , ','= '')
pac_all_backup$total <- str_replace_all(pac_all_backup$total, col_um)
pac_all_backup$dems <- str_replace_all(pac_all_backup$dems, col_um)
pac_all_backup$repubs <- str_replace_all(pac_all_backup$repubs, col_um)

 pac_all_backup <- transform(pac_all_backup, total = as.numeric(total), 
               dems = as.numeric(dems), repubs = as.numeric(repubs))

print(pac_all_backup)

```


_Remove this text, and add your answer for Exercise 3 here._

### Exercise 4

```{r hw3-ex4}
pac_all_backup %>% 
  separate(country_parent, into = c('Country', 'parent'), sep = "/" )
col_um = c("[$]"='' , ','= '')
pac_all_backup$total <- str_replace_all(pac_all_backup$total, col_um)
pac_all_backup$dems <- str_replace_all(pac_all_backup$dems, col_um)
pac_all_backup$repubs <- str_replace_all(pac_all_backup$repubs, col_um)

 pac_all_backup <- transform(pac_all_backup, total = as.numeric(total), 
               dems = as.numeric(dems), repubs = as.numeric(repubs)) 

   geom_line(filter(pac_all_backup, country == "Canada"), aes(x = year , y = total, fill = country )) +
  labs(
    x = "Loan amount ($)",
    y = "Density",
    title = "Amounts of Lending Club loans"
  )

  

```


_Remove this text, and add your answer for Exercise 4 here._

### Exercise 5

```{r hw3-ex5}
# remove this comment and add the code for Exercise 5 here

```


_Remove this text, and add your answer for Exercise 5 here._

